### ISSUE TITLE
Possible to set manual axes ranges?

### ISSUE THREAD

**Issue by alexander-roth** [grantmcdermott/ggiplot#17]
Is it possible to manually set the range of the axis in a plot? In `ggplot` this is possible with `ylim`/`xlim` and I was wondering whether this option is also available in `ggiplot`? I did not find any setting for that and I hope I didn't miss anything. Would it be possible to set this option during the creation of the plot or are you aware of a way to change it after creating the plot? I tried using `ylim.add`, corresponding to `iplot()`, yet this didn't work in my case.

**Comment by grantmcdermott** [comment]
Just add `xlim`/`ylim` after your ggiplot call. For example, 

```r
ggiplot(...) + 
   xlim(-100, 100)
```

will extend (clip?) your x-axis to -100:100. Remember that ggiplot yields a standard ggolot2 object, so all of the standard methods apply. https://ggplot2.tidyverse.org/reference/lims.html

**Comment by alexander-roth** [comment]
Thanks, @grantmcdermott for your answer. That's indeed the most obvious option which I missed. Now it works as expected, thanks again!

**Comment by grantmcdermott** [comment]
Excellent. Don't hesitate to open another issue if something else comes up.
