### ISSUE TITLE
Bug when periods of two models are not equal

### ISSUE THREAD

**Issue by alexander-roth** [grantmcdermott/ggiplot#18]
Hi @grantmcdermott, 

I found a little issue plotting two models in the same figure with `ggiplot` when they have an unequal period cover:

* Model 1 ("Many years") covers the periods -8 until +12
* Model 2 ("Fewer years") covers the periods -4 until +8

Using *iplot*, I get the following expected figure:

```
iplot(list("Many years"  = reg_out1,
           "Fewer years" = reg_out2),
           main = 'Staggered treatment', ref.line = 0, pt.join = TRUE)
legend('bottom', col = c(1, 2), pch = c(20, 17),
       legend = c('Many years', 'Fewer years'))
```
![grafik](https://user-images.githubusercontent.com/57187600/221936053-c16c7882-3976-41b2-ab97-79b4908a340c.png)

With *ggiplot*, neither the figure, nor the legend is rightly created:

```
ggiplot(list("Many years" = reg_out1,reg_out2),
        main  = 'Staggered treatment', ref.line = 0, pt.join = TRUE,
        theme = theme_minimal() + theme(legend.position = "bottom"))
```
![grafik](https://user-images.githubusercontent.com/57187600/221935921-f138c790-2f70-429d-95ed-bd42aadd3b5c.png)

Is that a bug or did I do something wrong?

**Comment by grantmcdermott** [comment]
Hmmm. Can you check that you are using the latest version of the package? I would have thought that this was fixed by https://github.com/grantmcdermott/ggiplot/pull/10.

**Comment by alexander-roth** [comment]
Thanks @grantmcdermott, that solved it!
