### ISSUE TITLE
Error when using (log) in the dependent variable

### ISSUE THREAD

**Issue by caleb-kwon** [grantmcdermott/ggiplot#20]
Hi Grant!

Thanks for your wonderful package. I love how your package introduces increased flexibility to output Laurent's wonderful fixest objects.

I seem to be getting a bug, however, when applying the log transform to the dependent variable inside the `feols` function. For example:

#### Bug

```
reg <- DT |> feols(log(sales) ~  i(week_ind, treat, -1 )  |store + week_ind)

ggiplot(reg)

Error in `$<-.data.frame`(`*tmp*`, "lhs", value = c("log", "sales" : 
  replacement has 2 rows, data has 31

```

#### No Bug
```
reg <- DT |> feols(sales ~  i(week_ind, treat, -1 )  |store + week_ind)

ggiplot(reg)
```

But maybe this is not a bug, but a feature!

Thank you again!

**Comment by grantmcdermott** [comment]
Bug confirmed. Thanks Caleb. I'll fix this when I get a chance.

**Comment by grantmcdermott** [comment]
Sorry for taking so long to get back to this @caleb-kwon . It should be fixed in the latest dev version (available immediately via `remotes::install_github(...)` or in a hour or so from r-universe ). Feel free to re-open if you're still running into issues.
