### ISSUE TITLE
ggiplot works very well (thank you) except when I want to add an "aggr_eff"

### ISSUE THREAD

**Issue by BakouMert** [grantmcdermott/ggiplot#21]
Dear,

First of all, thank you for your fantastic work on this package. Making beautiful and readable graphs is important, and you make that a lot easier. I use the Sun and Abraham version of staggered difference in differences using the fixest package. ggiplot(model) works fine, and I can add all kinds of ggplot layers. However, I do have a little issue (that I didn't have a few months back):

When trying to add an aggr_eff (e.g. ggiplot(model, aggr_eff = "post"), I get the following error message:

>  Error: The jacobian does not match the variance-covariance matrix.
> In addition: There were 31 warnings (use warnings() to see them)

warnings() then yields 31 times:

> In names(model[["coefficients"]]) == names(coefs) :
>   longer object length is not a multiple of shorter object length

I am not well versed enough as to what happens under the hood to understand what could cause this issue? Any ideas/recommendations? 

Thank you very much in advance and kind regards,
BakouM

**Comment by grantmcdermott** [comment]
Hi @BakouMert thanks for the kind words and sorry for taking so long to respond. It's very tricky to troubleshoot here without more information. Could you post a reprex, or at least show the results of `coeftable(mod)` and `iplot_data(mod)`?

**Comment by grantmcdermott** [comment]
Closing in the absence of more info. Feel free to reply with more info and I'll reopen.
