### ISSUE TITLE
Coef-filter

### ISSUE THREAD

**Issue by inkrement** [grantmcdermott/ggiplot#22]
It seems like iplots's keep and drop arguments are not supported yet. Is there an easy way to plot only a specific (relative) time period around an event?

**Comment by grantmcdermott** [comment]
Thanks for raising the issue. Should be working if you grab the latest dev version now.

``` r
library(fixest)
library(ggiplot)
#> Loading required package: ggplot2

est_did = feols(y ~ x1 + i(period, treat, 5) | id + period, base_did)

ggiplot(est_did)
```

![](https://i.imgur.com/ZaQ6IWz.png)

``` r

ggiplot(est_did, keep = "4|5|6")
```

![](https://i.imgur.com/qJgP84X.png)

``` r

ggiplot(est_did, drop = "1")
```

![](https://i.imgur.com/s3DNYaU.png)

<sup>Created on 2023-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
