### ISSUE TITLE
Install `ggiplot` on R running on Linux system

### ISSUE THREAD

**Issue by lwiancheng** [grantmcdermott/ggiplot#23]
Hi,

I tried to install `ggiplot` on R (version 4.0.4) running on a Linux-based HPC server. During the installation, I received the following error:
`Error in parse(outFile) :
  /tmp/RtmpCYgtH1/R.INSTALL8975b72873f/ggiplot/R/aggr_es.R:94:28: unexpected input
93:     ## mostly for the "both" case)
94:     hyp_attr = sapply(res, \
`

As a result, it reports: `ERROR: unable to collate and parse R files for package 'ggiplot' `.

The latest R version available on the server is a little bit old so I am wondering is it because `ggiplot` is not compatible with this old version R? Btw, I successfully installed `ggiplot` on my own laptop running on Windows with R-4.2.2.

Thank you for your attention.

**Comment by grantmcdermott** [comment]
Hi @lwiancheng, sorry to hear that you're running into problems. It's tough for me to troubleshoot without more information, though. Which distro is your HPC running etc?

I don't _think_ there should be any restrictions on R>=4.0.0 and the package is certainly working on Ubuntu.

The `aggr_es` function is basically a thin wrapper around `marginaleffects::hypotheses`. Are you able to install the **marginaleffects** package on its own and run those functions?

**Comment by grantmcdermott** [comment]
Closing in the absence of more information. Please lmk if you're still having trouble and have been able to try some of my suggestions above.
