### ISSUE TITLE
Add support for pt.size or similar argument

### ISSUE THREAD

**Issue by jcvdav** [grantmcdermott/ggiplot#26]
Hi Grant - 

Not an issue, mor like a feature request / enhancement...

I've been (ab)using this plot quite a bit. The default parameters are generally fine, but I'd like to have some more control over the aesthetics.  I see [here](https://github.com/grantmcdermott/ggiplot/blob/main/R/ggiplot.R#L322) that the default is to use a `ptsize = 2.5` (with adjustments for faceted versions). This is a bit annoying because it overrides what's been established by `ggplot2::update_geom_defaults(geom = "point", list(size = 4))`, for example.

Since there is already an argument for `pt.pch`, would it be possible to include one for `pt.size` (or similar)?
Alternatively, perhaps having `ptsize` be determined by `GeomPoint$default_aes` and then perform the facet-induced reductions when needed? 

I see you are planning on submitting to CRAN soon, and I wouldn't want to derail that. But if you think it would be acceptable, I'd be happy to submit a PR.

**Comment by grantmcdermott** [comment]
> But if you think it would be acceptable, I'd be happy to submit a PR.

Yeah, please go for it JC. I've been derailed with the CRAN plans, but will try to look again soon.

**Comment by jcvdav** [comment]
Sounds good. I'll draft something up.
