### ISSUE TITLE
Change package name to ggfixest

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/ggiplot#29]
With the addition of more general coefficient plot support (#28), it probably makes sense to change the package name to ~~**ggcoefplot**~~ (UPDATE: **ggfixest**) before submitting to CRAN.

PROS

- Closer alignment with the upstream **fixest** docs and function logic, i.e. `iplot` is nested within `coefplot` as a special case.
- Package functionality more immediately grok-able for those that come across it. (Most people understand what a "coefplot" is, whereas "iplot" is more insider baseball.)

CONS

- A pain for backwards compatibility (albeit tempered by the fact that we haven't submitted to CRAN yet). Might make sense  just to archive this repo in its current state as read only, leave a prominent note about the new repo location, and copy across the full version history to `github.com/grantmcdermott/ggfixest`.
- Minor: 1) Will have to shuffle around some internal docs. 2) Will have to update a few external website links.

**Comment by grantmcdermott** [comment]
I'm leaning towards "yes", i.e. change the package name to "ggcoefplot" and then submit to CRAN.

Wondering if @lrberge or existing users have any thoughts/objections? @caleb-kwon @jcvdav @alexander-roth @simonheb

**Comment by jcvdav** [comment]
Renaming to `ggcoefplot` seems logical.

**Comment by grantmcdermott** [comment]
Another option: ggfixest

**Comment by grantmcdermott** [comment]
Ha, ain't gonna happen!

In seriousness, I think other options like [`see`](https://easystats.github.io/see/articles/parameters.html) already do a good job of providing generic coefficient plot support across many model classes. For me, as a dedicated `fixest` user, the benefit of this package lies in the additional features unlocked by this specific and tight integration.

**Comment by etiennebacher** [comment]
Just my 2 cents: I find `ggcoefplot` very generic and maybe a bit misleading if the end goal is to provide support only for `fixest` objects (which is completely fine for me, there are already several packages for plotting regression results).

I think `ggfixest` clearly sets the expectations: it provides `ggplot2` support for `fixest` objects.

**Comment by grantmcdermott** [comment]
Thanks all.

End result: The package name has been changed to **ggfixest** and is now available on CRAN.

**Comment by etiennebacher** [comment]
Awesome, thanks @grantmcdermott !
