### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/ggiplot#8]
Use @vincentarelbundock's https://github.com/vincentarelbundock/tinyviztest for figs

**Comment by vincentarelbundock** [comment]
Note that I've been having problems with this. The tests run interactively, but when I run the whole test suite it fails with this weird error, and I can't figure it out: 

https://github.com/markvanderloo/tinytest/issues/101

**Comment by vincentarelbundock** [comment]
FYI, I just opened a PR on the `tinytest` repo which, I hope, will solve the issue: https://github.com/markvanderloo/tinytest/pull/104

**Comment by grantmcdermott** [comment]
Thanks mate. On my work computer so haven't had a chance to follow up on your suggestions in https://github.com/vincentarelbundock/tinyviztest/issues/1. But will watch the PR closely.
